### ISSUE TITLE
All Post/Get Requests Pending After req.login Custom callback

### ISSUE THREAD

**Issue by JonasTheCuriousDev** [passport/www.passportjs.org#98]
As the title implies all of my Post / Get requests get the pending status after I have run req.login, it seems like there is something blocking them. 

I have also tried to use req.logIn which does not change anything. 
`
req.login(user, loginErr => {
        if (loginErr) {
          return next(loginErr);
        }
        return res.send({ success : true, message : 'authentication succeeded' });
      }) `

Full code
`
```
router.post('/login', function(req, res, next) {
    passport.authenticate('local', function(err, user, info) {
      if (err) {
        return next(err);
      }
```

      if (! user) {
        return res.send({ success : false, message : info.message });
      }
      
      req.login(user, loginErr => {
        if (loginErr) {
          return next(loginErr);
        }
        return res.send({ success : true, message : 'authentication succeeded' });
      })

    })(req, res, next);
  });
`
Am I missing something or is req.login actually bugged? 

I have also submitted a stackoverflow question which can be viewed here: 
[Stackoverflow](https://stackoverflow.com/questions/64304872/all-post-get-requests-pending-after-req-login-passport-react-nodejs)

**Comment by xDsquare** [comment]
Hey @JonasTheCuriousDev ,

I'm writing you here cause I did not find any other option to contact you.

I'm currently trying to create a crash game and I saw your stackoverflow / p5js and wanted to asked if you managed to make any progress because I'm also struggling with getting the scales to display the correct values.

I would be really thankful if you could reach out to me via email (alex@xdsquare.pw) or discord (xdsquare#2222).

- Alex

**Comment by jaredhanson** [comment]
It looks like you figured out a solution, based on your answer on StackOverflow. Closing.
